### PR TITLE
Added missing finnish translations

### PR DESCRIPTION
**Pull request by srpg**

### CODE REVIEW

**Comment by ThaPwned** [comment]
Thanks! I noticed this:
https://github.com/ThaPwned/WCS/blob/58d6decbf11c1a179a0d623cf8b1dcef2d4fce36/resource/source-python/translations/wcs/menu_strings.ini#L416-L419 and would appreciate it if you'd modify it, so it doesn't say the same as this one:
https://github.com/ThaPwned/WCS/blob/58d6decbf11c1a179a0d623cf8b1dcef2d4fce36/resource/source-python/translations/wcs/menu_strings.ini#L412-L415

**Comment by srpg** [comment]
Now its modifyed to correct, i didn't see that had same text

**Comment by ThaPwned** [comment]
My Finnish is a bit rusty but I'm pretty sure "shopmenu" doesn't translate into "raceinfo", hehe.

**Comment by srpg** [comment]
Which line it says raceinfo, you are correct in finnish, it should be kauppa menu instead raceinfo

**Comment by ThaPwned** [comment]
Right here: https://github.com/ThaPwned/WCS/blob/ff96c78dba4ff9259602b283d00c26aecde15921/resource/source-python/translations/wcs/menu_strings.ini#L422

**Comment by srpg** [comment]
Now that line is fixed

**Comment by ThaPwned** [comment]
Thanks!

**Comment by srpg** [comment]
Btw i just found a mistypo finnish translate in config strings..

**Pull request merged**
